---
baseUrl: "http://localhost:8000"
app_port: 8000
monitoring_port: 8001
production: False
email_debug: True
template_default:
  baseUrl: "http://localhost:8000"
  staticPath: "/static"
  title: "Infratelier Consultant"
  description: "Web Consultant, Infrastructure Experts"
  siteName: "Infratelier Consultant"
  keywords: "Infratelier Consultant"
...
