apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: persistent-storage
  namespace: "{{.Values.namespace}}"
  annotations:
    volume.beta.kubernetes.io/storage-class: scw-bssd-retain
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
