apiVersion: v1
kind: Secret
metadata:
  name: cephfs-secret
  namespace: "{{.Values.namespace}}"
type: Opaque
data:
  "key": "{{.Values.cephsecret |b64enc}}"

---

apiVersion: v1
kind: Secret
metadata:
  name: registry-gitlab-cred
  namespace: "{{.Values.namespace}}"
type: kubernetes.io/dockerconfigjson
data:
  ".dockerconfigjson": {{.Values.gitlabdockerconfigjson}}
