kind: Service
apiVersion: v1
metadata:
  name: backend
  namespace: "{{.Values.namespace}}"
spec:
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

---

kind: Service
apiVersion: v1
metadata:
  name: frontend
  namespace: "{{.Values.namespace}}"
spec:
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
